project_id = "pfiemzykujhwhulfixxt"

[functions.audit-log]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-editorial-notification]
verify_jwt = false
